/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupAvatarRouteImport } from './routes/setup-avatar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatihanSoalRouteImport } from './routes/latihan-soal'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as LatihanSoalAnalyticsRouteImport } from './routes/latihan-soal_.analytics'
import { Route as LatihanSoalGradeRouteImport } from './routes/latihan-soal_.$grade'
import { Route as SubjectSubjectIdChapterIdRouteImport } from './routes/subject.$subjectId_.$chapterId'

const SetupAvatarRoute = SetupAvatarRouteImport.update({
  id: '/setup-avatar',
  path: '/setup-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanSoalRoute = LatihanSoalRouteImport.update({
  id: '/latihan-soal',
  path: '/latihan-soal',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanSoalAnalyticsRoute = LatihanSoalAnalyticsRouteImport.update({
  id: '/latihan-soal_/analytics',
  path: '/latihan-soal/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanSoalGradeRoute = LatihanSoalGradeRouteImport.update({
  id: '/latihan-soal_/$grade',
  path: '/latihan-soal/$grade',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdChapterIdRoute =
  SubjectSubjectIdChapterIdRouteImport.update({
    id: '/subject/$subjectId_/$chapterId',
    path: '/subject/$subjectId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/latihan-soal': typeof LatihanSoalRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/setup-avatar': typeof SetupAvatarRoute
  '/latihan-soal/$grade': typeof LatihanSoalGradeRoute
  '/latihan-soal/analytics': typeof LatihanSoalAnalyticsRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/subject/$subjectId/$chapterId': typeof SubjectSubjectIdChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/latihan-soal': typeof LatihanSoalRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/setup-avatar': typeof SetupAvatarRoute
  '/latihan-soal/$grade': typeof LatihanSoalGradeRoute
  '/latihan-soal/analytics': typeof LatihanSoalAnalyticsRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/subject/$subjectId/$chapterId': typeof SubjectSubjectIdChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/latihan-soal': typeof LatihanSoalRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/setup-avatar': typeof SetupAvatarRoute
  '/latihan-soal_/$grade': typeof LatihanSoalGradeRoute
  '/latihan-soal_/analytics': typeof LatihanSoalAnalyticsRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/subject/$subjectId_/$chapterId': typeof SubjectSubjectIdChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/landing'
    | '/latihan-soal'
    | '/login'
    | '/me'
    | '/settings'
    | '/setup-avatar'
    | '/latihan-soal/$grade'
    | '/latihan-soal/analytics'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/landing'
    | '/latihan-soal'
    | '/login'
    | '/me'
    | '/settings'
    | '/setup-avatar'
    | '/latihan-soal/$grade'
    | '/latihan-soal/analytics'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/landing'
    | '/latihan-soal'
    | '/login'
    | '/me'
    | '/settings'
    | '/setup-avatar'
    | '/latihan-soal_/$grade'
    | '/latihan-soal_/analytics'
    | '/subject/$subjectId'
    | '/subject/$subjectId_/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  LatihanSoalRoute: typeof LatihanSoalRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  SettingsRoute: typeof SettingsRoute
  SetupAvatarRoute: typeof SetupAvatarRoute
  LatihanSoalGradeRoute: typeof LatihanSoalGradeRoute
  LatihanSoalAnalyticsRoute: typeof LatihanSoalAnalyticsRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRoute
  SubjectSubjectIdChapterIdRoute: typeof SubjectSubjectIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-avatar': {
      id: '/setup-avatar'
      path: '/setup-avatar'
      fullPath: '/setup-avatar'
      preLoaderRoute: typeof SetupAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan-soal': {
      id: '/latihan-soal'
      path: '/latihan-soal'
      fullPath: '/latihan-soal'
      preLoaderRoute: typeof LatihanSoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan-soal_/analytics': {
      id: '/latihan-soal_/analytics'
      path: '/latihan-soal/analytics'
      fullPath: '/latihan-soal/analytics'
      preLoaderRoute: typeof LatihanSoalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan-soal_/$grade': {
      id: '/latihan-soal_/$grade'
      path: '/latihan-soal/$grade'
      fullPath: '/latihan-soal/$grade'
      preLoaderRoute: typeof LatihanSoalGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId_/$chapterId': {
      id: '/subject/$subjectId_/$chapterId'
      path: '/subject/$subjectId/$chapterId'
      fullPath: '/subject/$subjectId/$chapterId'
      preLoaderRoute: typeof SubjectSubjectIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  LatihanSoalRoute: LatihanSoalRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  SettingsRoute: SettingsRoute,
  SetupAvatarRoute: SetupAvatarRoute,
  LatihanSoalGradeRoute: LatihanSoalGradeRoute,
  LatihanSoalAnalyticsRoute: LatihanSoalAnalyticsRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRoute,
  SubjectSubjectIdChapterIdRoute: SubjectSubjectIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
